In [3]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.model_selection import train_test_split

In [5]:
from sklearn.datasets import load_boston
boston = load_boston()
boston

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [8]:
df_X = pd.DataFrame(boston.data,columns=boston.feature_names)
df_Y = pd.DataFrame(boston.target)

In [10]:
df_X.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT  
count  506.000000  
mean    12.653063  
std      7.141062  
min      1.730000  
25%      6.950000  
50%     11.360000  
75%     16.955000  
max     37.970000

In [12]:
rg = linear_model.LinearRegression()

In [62]:
x_train, x_test, y_train, y_test = train_test_split(df_X, df_Y, test_size=0.2, random_state=20)


In [63]:
df_X.shape

(506, 13)

In [64]:
df_Y.shape

(506, 1)

In [65]:
x_train.shape

(404, 13)

In [66]:
y_train.shape

(404, 1)

In [67]:
x_train.transpose()

7         268        80         30         450       140  \
CRIM       0.14455    0.5405    0.04113    1.13081    6.71772    0.2909   
ZN        12.50000   20.0000   25.00000    0.00000    0.00000    0.0000   
INDUS      7.87000    3.9700    4.86000    8.14000   18.10000   21.8900   
CHAS       0.00000    0.0000    0.00000    0.00000    0.00000    0.0000   
NOX        0.52400    0.5750    0.42600    0.53800    0.71300    0.6240   
RM         6.17200    7.4700    6.72700    5.71300    6.74900    6.1740   
AGE       96.10000   52.6000   33.50000   94.10000   92.60000   93.6000   
DIS        5.95050    2.8720    5.40070    4.23300    2.32360    1.6119   
RAD        5.00000    5.0000    4.00000    4.00000   24.00000    4.0000   
TAX      311.00000  264.0000  281.00000  307.00000  666.00000  437.0000   
PTRATIO   15.20000   13.0000   19.00000   21.00000   20.20000   21.2000   
B        396.90000  390.3000  396.90000  360.17000    0.32000  388.0800   
LSTAT     19.15000    3.1600    5.29000   22.60000   17.44000   24.1600   

               397        360        329        307  ...        278  \
CRIM       7.67202    4.54192    0.06724    0.04932  ...    0.07978   
ZN         0.00000    0.00000    0.00000   33.00000  ...   40.00000   
INDUS     18.10000   18.10000    3.24000    2.18000  ...    6.41000   
CHAS       0.00000    0.00000    0.00000    0.00000  ...    0.00000   
NOX        0.69300    0.77000    0.46000    0.47200  ...    0.44700   
RM         5.74700    6.39800    6.33300    6.84900  ...    6.48200   
AGE       98.90000   88.00000   17.20000   70.30000  ...   32.10000   
DIS        1.63340    2.51820    5.21460    3.18270  ...    4.14030   
RAD       24.00000   24.00000    4.00000    7.00000  ...    4.00000   
TAX      666.00000  666.00000  430.00000  222.00000  ...  254.00000   
PTRATIO   20.20000   20.20000   16.90000   18.40000  ...   17.60000   
B        393.10000  374.56000  375.21000  396.90000  ...  396.90000   
LSTAT     19.92000    7.79000    7.34000    7.53000  ...    7.19000   

               331       404        393        218       412       223  \
CRIM       0.05023   41.5292    8.64476    0.11069   18.8110    0.6147   
ZN        35.00000    0.0000    0.00000    0.00000    0.0000    0.0000   
INDUS      6.06000   18.1000   18.10000   13.89000   18.1000    6.2000   
CHAS       0.00000    0.0000    0.00000    1.00000    0.0000    0.0000   
NOX        0.43790    0.6930    0.69300    0.55000    0.5970    0.5070   
RM         5.70600    5.5310    6.19300    5.95100    4.6280    6.6180   
AGE       28.40000   85.4000   92.60000   93.80000  100.0000   80.8000   
DIS        6.64070    1.6074    1.79120    2.88930    1.5539    3.2721   
RAD        1.00000   24.0000   24.00000    5.00000   24.0000    8.0000   
TAX      304.00000  666.0000  666.00000  276.00000  666.0000  307.0000   
PTRATIO   16.90000   20.2000   20.20000   16.40000   20.2000   17.4000   
B        394.02000  329.4600  396.90000  396.90000   28.7900  396.9000   
LSTAT     12.43000   27.3800   15.17000   17.92000   34.3700    7.6000   

               271        474        355  
CRIM       0.16211    8.05579    0.10659  
ZN        20.00000    0.00000   80.00000  
INDUS      6.96000   18.10000    1.91000  
CHAS       0.00000    0.00000    0.00000  
NOX        0.46400    0.58400    0.41300  
RM         6.24000    5.42700    5.93600  
AGE       16.30000   95.40000   19.50000  
DIS        4.42900    2.42980   10.58570  
RAD        3.00000   24.00000    4.00000  
TAX      223.00000  666.00000  334.00000  
PTRATIO   18.60000   20.20000   22.00000  
B        396.90000  352.58000  376.04000  
LSTAT      6.59000   18.14000    5.57000  

[13 rows x 404 columns]

In [68]:
y_train.transpose()

7     268   80    30    450   140  397   360   329   307  ...   278   331  \
0  27.1  43.5  28.0  12.7  13.4  14.0  8.5  25.0  22.6  28.2  ...  29.1  17.1   

   404   393   218   412   223   271   474   355  
0  8.5  13.8  21.5  17.9  30.1  25.2  13.8  20.6  

[1 rows x 404 columns]

In [69]:
x_train.shape

(404, 13)

In [70]:
rg.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [71]:
rg.coef_

array([[-6.99238421e-02,  4.08478370e-02,  4.69344473e-02,
         2.94877232e+00, -2.12030473e+01,  3.75149147e+00,
         1.86497729e-02, -1.33522845e+00,  2.71771943e-01,
        -1.12289557e-02, -9.01973881e-01,  9.09628104e-03,
        -5.66286361e-01]])

In [72]:
prediction = rg.predict(x_test)

In [73]:
prediction

array([[21.05690762],
       [27.54410192],
       [20.16232248],
       [23.91885465],
       [13.00416782],
       [19.97164958],
       [17.74585525],
       [ 7.14393596],
       [18.91550072],
       [25.14388009],
       [27.58099651],
       [15.86799568],
       [23.66924873],
       [21.50832445],
       [20.12745896],
       [25.14885921],
       [31.19702709],
       [19.51664234],
       [14.51270678],
       [17.36388805],
       [38.06837294],
       [42.54263219],
       [27.22576394],
       [32.41179632],
       [26.52857019],
       [26.82709884],
       [19.98770946],
       [25.15283706],
       [21.28068136],
       [24.34416726],
       [20.27481846],
       [17.23907825],
       [22.82269451],
       [ 9.58700562],
       [30.18955497],
       [20.40165818],
       [42.65039536],
       [22.27926124],
       [19.51132656],
       [31.13475442],
       [ 8.44358819],
       [16.84928291],
       [17.27751358],
       [12.95855964],
       [22.82880927],
       [28

In [83]:
prediction[0]

array([21.05690762])

In [76]:
y_test

0
498  21.2
94   20.6
150  21.5
221  21.7
423  13.4
13   20.4
209  20.0
398   5.0
31   14.5
235  24.0
181  36.2
495  23.1
326  23.0
29   21.0
336  19.5
56   24.7
284  32.2
478  14.6
129  14.3
17   17.5
226  37.6
204  50.0
90   22.6
197  30.3
216  23.3
311  22.1
14   18.2
321  23.1
319  21.0
254  21.9
..    ...
74   24.1
322  20.4
115  18.3
84   23.9
501  22.4
240  22.0
92   22.9
362  20.8
148  17.8
34   13.5
342  16.5
147  14.6
503  23.9
185  29.6
241  20.1
422  20.8
72   22.8
169  22.3
76   20.0
473  29.8
19   18.2
439  12.8
505  11.9
81   23.9
323  18.5
9    18.9
449  13.0
359  22.6
106  19.5
314  23.8

[102 rows x 1 columns]

In [84]:
# Mean square error

np.mean((prediction-y_test)**2)

0    16.495352
dtype: float64